### ISSUE TITLE
How to create arrow paths with LinePath2D?

### ISSUE THREAD

**Issue by elue6857** [cloudofoz/godot-linepath-2d#1]
Hi, thanks for sharing the LinePath2D plugin! I'm new to Godot and was wondering how to create paths with arrows like in your example images. Any tips?

Thanks!

**Comment by cloudofoz** [comment]
Hi, I am glad you like it.

You can attach any shape or sprite to the LinePath2D, arrows included.
1. Add a PathFollow2D as a child node of the LinePath2D
2. Add your shape (a triangle, for example) as a child of the PathFollow2D
3. Adjust the Progress Ratio field of the PathFollow2D from 0.0 (the triangle will stay at the beginning of the line) to 1.0 (the triangle will be placed at the end of the line).

Let me know if this solved your problem!

**Comment by elue6857** [comment]
> Hi, I am glad you like it.
> 
> You can attach any shape or sprite to the LinePath2D, arrows included.
> 
> 1. Add a PathFollow2D as a child node of the LinePath2D
> 2. Add your shape (a triangle, for example) as a child of the PathFollow2D
> 3. Adjust the Progress Ratio field of the PathFollow2D from 0.0 (the triangle will stay at the beginning of the line) to 1.0 (the triangle will be placed at the end of the line).
> 
> Let me know if this solved your problem!

Thanks for the help! My issue is resolved now.Have a nice day!
