### ISSUE TITLE
Cannot change parameter values in inspector

### ISSUE THREAD

**Issue by gatomesa** [cloudofoz/godot-linepath-2d#2]
Godot v4.3.stable - macOS 14.6.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

When trying to set the values of parameters in the inspector, the value always goes right back to the default one.

https://github.com/user-attachments/assets/7d7fce35-f825-4737-a0bb-6f67dd291bfd

**Comment by cloudofoz** [comment]
I'm sorry for not responding earlier; I've been very busy. I just tested this add-on with Godot v4.3, and it appears to work without any problems on my machine. If you encounter any issues again, please try to attach your scene so I can better investigate any potential problems.

**Comment by gatomesa** [comment]
Thanks for answering. The bug fixed itself by closing and reopening the editor, so I closed the issue.

**Comment by cloudofoz** [comment]
I'm glad you solved your problem!
